/* Canonical ingredient vocabulary, synonyms for receipt OCR matching,
   default pantry staples, and the recipe database. */

const SYNONYMS = {
  chicken: ["chicken breast", "chicken thighs", "chicken thigh", "rotisserie chicken", "chicken tenders", "whole chicken"],
  beef: ["ground beef", "hamburger", "steak", "sirloin", "chuck roast", "beef"],
  pork: ["pork chop", "pork loin", "ground pork", "pork"],
  bacon: ["bacon"],
  sausage: ["italian sausage", "sausage", "chorizo"],
  shrimp: ["shrimp", "prawns"],
  salmon: ["salmon fillet", "salmon"],
  tuna: ["canned tuna", "tuna steak", "tuna"],
  eggs: ["eggs", "egg"],
  tofu: ["firm tofu", "tofu"],
  rice: ["white rice", "brown rice", "jasmine rice", "long grain rice", "basmati", "rice"],
  pasta: ["spaghetti", "penne", "macaroni", "fettuccine", "rigatoni", "pasta"],
  noodles: ["ramen", "egg noodles", "rice noodles", "udon", "noodles"],
  bread: ["sandwich bread", "baguette", "sourdough", "bread"],
  tortillas: ["flour tortillas", "corn tortillas", "tortillas"],
  potatoes: ["russet potatoes", "yukon potatoes", "red potatoes", "potatoes", "potato"],
  "sweet potato": ["sweet potatoes", "sweet potato", "yams"],
  oats: ["rolled oats", "oatmeal", "oats"],
  flour: ["all-purpose flour", "flour"],
  onion: ["yellow onion", "red onion", "white onion", "shallot", "onions", "onion"],
  garlic: ["garlic"],
  tomatoes: ["roma tomatoes", "cherry tomatoes", "grape tomatoes", "beefsteak tomatoes", "tomatoes", "tomato"],
  "canned tomatoes": ["diced tomatoes", "crushed tomatoes", "tomato sauce", "canned tomatoes"],
  "bell pepper": ["green bell pepper", "red bell pepper", "bell peppers", "bell pepper"],
  carrots: ["baby carrots", "carrots", "carrot"],
  celery: ["celery"],
  broccoli: ["broccoli florets", "broccoli"],
  spinach: ["baby spinach", "spinach"],
  lettuce: ["romaine", "iceberg lettuce", "butter lettuce", "lettuce"],
  cucumber: ["cucumber", "cucumbers"],
  zucchini: ["zucchini"],
  mushrooms: ["portobello", "button mushrooms", "cremini", "mushrooms", "mushroom"],
  avocado: ["hass avocado", "avocado"],
  lemon: ["meyer lemon", "lemon"],
  lime: ["lime"],
  cheese: ["shredded cheese", "cheese blend", "cheese"],
  cheddar: ["cheddar cheese", "cheddar"],
  mozzarella: ["mozzarella"],
  parmesan: ["parmesan", "parmigiano"],
  milk: ["whole milk", "2% milk", "milk"],
  butter: ["butter"],
  cream: ["heavy cream", "whipping cream", "cream"],
  yogurt: ["greek yogurt", "yogurt"],
  beans: ["black beans", "kidney beans", "pinto beans", "canned beans", "beans"],
  lentils: ["red lentils", "green lentils", "lentils"],
  chickpeas: ["chickpeas", "garbanzo beans"],
  salsa: ["salsa"],
  "olive oil": ["extra virgin olive oil", "olive oil"],
  "vegetable oil": ["canola oil", "vegetable oil"],
  salt: ["salt"],
  pepper: ["black pepper", "pepper"],
  "soy sauce": ["soy sauce"],
  sugar: ["sugar"],
  honey: ["honey"],
  "peanut butter": ["peanut butter"],
  ketchup: ["ketchup"],
  mustard: ["mustard", "dijon"],
  mayo: ["mayonnaise", "mayo"],
  "hot sauce": ["hot sauce", "sriracha"],
  stock: ["chicken stock", "vegetable stock", "chicken broth", "broth", "stock"],
  "rice vinegar": ["rice vinegar"],
  "coconut milk": ["coconut milk"],
  "curry powder": ["curry powder"],
  cumin: ["cumin"],
  paprika: ["paprika", "smoked paprika"],
  oregano: ["oregano"],
  basil: ["basil"],
  cilantro: ["cilantro"],
  parsley: ["parsley"],
  thyme: ["thyme"],
  "chili powder": ["chili powder"],
  ginger: ["fresh ginger", "ginger"],
};

/* Pantry staples offered as checkboxes, grouped. `checked` = default on. */
const PANTRY_GROUPS = [
  {
    name: "Oils, vinegars & basics",
    items: [
      { item: "olive oil", checked: true },
      { item: "vegetable oil", checked: true },
      { item: "salt", checked: true },
      { item: "pepper", checked: true },
      { item: "soy sauce", checked: true },
      { item: "rice vinegar", checked: false },
    ],
  },
  {
    name: "Spices & flavor",
    items: [
      { item: "garlic", checked: true },
      { item: "onion", checked: true },
      { item: "cumin", checked: false },
      { item: "paprika", checked: false },
      { item: "oregano", checked: false },
      { item: "basil", checked: false },
      { item: "chili powder", checked: false },
      { item: "curry powder", checked: false },
      { item: "ginger", checked: false },
      { item: "cilantro", checked: false },
      { item: "parsley", checked: false },
    ],
  },
  {
    name: "Dairy & eggs",
    items: [
      { item: "eggs", checked: true },
      { item: "butter", checked: true },
      { item: "milk", checked: true },
      { item: "cheese", checked: false },
      { item: "parmesan", checked: false },
      { item: "yogurt", checked: false },
      { item: "cream", checked: false },
    ],
  },
  {
    name: "Carbs",
    items: [
      { item: "rice", checked: true },
      { item: "pasta", checked: true },
      { item: "bread", checked: true },
      { item: "tortillas", checked: false },
      { item: "oats", checked: false },
      { item: "flour", checked: false },
      { item: "noodles", checked: false },
      { item: "potatoes", checked: false },
    ],
  },
  {
    name: "Canned & jarred",
    items: [
      { item: "canned tomatoes", checked: true },
      { item: "beans", checked: false },
      { item: "lentils", checked: false },
      { item: "chickpeas", checked: false },
      { item: "stock", checked: false },
      { item: "coconut milk", checked: false },
      { item: "salsa", checked: false },
      { item: "tuna", checked: false },
    ],
  },
  {
    name: "Condiments & sweeteners",
    items: [
      { item: "honey", checked: false },
      { item: "sugar", checked: false },
      { item: "peanut butter", checked: false },
      { item: "ketchup", checked: false },
      { item: "mustard", checked: false },
      { item: "mayo", checked: false },
      { item: "hot sauce", checked: false },
    ],
  },
];

const RECIPES = [
  /* ---------------- BREAKFAST ---------------- */
  {
    id: "veggie-omelet", name: "Veggie Omelet", type: "breakfast",
    time: "15 min", serves: 2,
    ingredients: [
      { item: "eggs", qty: "4" },
      { item: "bell pepper", qty: "1/2, diced" },
      { item: "onion", qty: "1/4, diced" },
      { item: "cheese", qty: "1/4 cup" },
      { item: "butter", qty: "1 tbsp" },
    ],
    steps: [
      "Whisk eggs with a pinch of salt and pepper.",
      "Melt butter in a skillet over medium heat; saute bell pepper and onion 3 minutes.",
      "Pour in eggs, tilt to spread, and cook until just set, about 3 minutes.",
      "Sprinkle cheese over half, fold, and slide onto a plate.",
    ],
  },
  {
    id: "avocado-toast", name: "Avocado Toast with Egg", type: "breakfast",
    time: "10 min", serves: 1,
    ingredients: [
      { item: "bread", qty: "2 slices" },
      { item: "avocado", qty: "1/2" },
      { item: "eggs", qty: "1" },
      { item: "lemon", qty: "1 wedge" },
      { item: "pepper", qty: "to taste" },
    ],
    steps: [
      "Toast the bread and fry the egg to your liking.",
      "Smash avocado onto toast with lemon juice, salt, and pepper.",
      "Top with the fried egg and serve.",
    ],
  },
  {
    id: "overnight-oats", name: "Overnight Oats", type: "breakfast",
    time: "5 min + overnight", serves: 2,
    ingredients: [
      { item: "oats", qty: "1 cup" },
      { item: "milk", qty: "1 cup" },
      { item: "yogurt", qty: "1/2 cup" },
      { item: "honey", qty: "2 tbsp" },
    ],
    steps: [
      "Stir everything together in a jar or bowl.",
      "Refrigerate overnight (at least 6 hours).",
      "Stir and eat cold, topped with anything you like.",
    ],
  },
  {
    id: "breakfast-burrito", name: "Breakfast Burrito", type: "breakfast",
    time: "20 min", serves: 2,
    ingredients: [
      { item: "tortillas", qty: "2 large" },
      { item: "eggs", qty: "4, scrambled" },
      { item: "beans", qty: "1/2 cup" },
      { item: "cheese", qty: "1/4 cup" },
      { item: "salsa", qty: "1/4 cup" },
    ],
    steps: [
      "Warm beans in a small pan; scramble eggs in a skillet.",
      "Warm tortillas directly over a gas flame or in a dry pan.",
      "Fill with eggs, beans, cheese, and salsa; roll up tightly.",
    ],
  },
  {
    id: "pancakes", name: "Fluffy Pancakes", type: "breakfast",
    time: "20 min", serves: 4,
    ingredients: [
      { item: "flour", qty: "1 1/2 cups" },
      { item: "eggs", qty: "1" },
      { item: "milk", qty: "1 1/4 cups" },
      { item: "butter", qty: "3 tbsp, melted" },
      { item: "sugar", qty: "2 tbsp" },
    ],
    steps: [
      "Whisk flour, sugar, salt, egg, milk, and melted butter until just combined.",
      "Heat a buttered skillet over medium heat.",
      "Pour 1/4-cup scoops; flip when bubbles appear, about 2 minutes per side.",
    ],
  },
  {
    id: "yogurt-bowl", name: "Honey Yogurt Bowl", type: "breakfast",
    time: "5 min", serves: 1,
    ingredients: [
      { item: "yogurt", qty: "1 cup" },
      { item: "honey", qty: "1 tbsp" },
      { item: "oats", qty: "1/4 cup, toasted" },
    ],
    steps: [
      "Spoon yogurt into a bowl.",
      "Drizzle with honey and top with toasted oats.",
    ],
  },
  /* ---------------- LUNCH ---------------- */
  {
    id: "chicken-caesar-salad", name: "Chicken Caesar Salad", type: "lunch",
    time: "20 min", serves: 2,
    ingredients: [
      { item: "chicken", qty: "1 breast" },
      { item: "lettuce", qty: "1 head, chopped" },
      { item: "parmesan", qty: "1/4 cup" },
      { item: "bread", qty: "2 slices, cubed" },
      { item: "lemon", qty: "1/2" },
      { item: "olive oil", qty: "2 tbsp" },
    ],
    steps: [
      "Season chicken with salt and pepper; sear 6 minutes per side, then slice.",
      "Toss bread cubes with olive oil and toast until crisp.",
      "Toss lettuce with lemon juice, olive oil, and parmesan; top with chicken and croutons.",
    ],
  },
  {
    id: "tuna-melt", name: "Tuna Melt", type: "lunch",
    time: "15 min", serves: 2,
    ingredients: [
      { item: "tuna", qty: "1 can, drained" },
      { item: "bread", qty: "4 slices" },
      { item: "cheese", qty: "4 slices" },
      { item: "mayo", qty: "2 tbsp" },
    ],
    steps: [
      "Mix tuna with mayo, salt, and pepper.",
      "Pile onto bread, top with cheese, and close the sandwiches.",
      "Grill in a buttered skillet until golden and melty, 3 minutes per side.",
    ],
  },
  {
    id: "fried-rice", name: "Vegetable Fried Rice", type: "lunch",
    time: "20 min", serves: 4,
    ingredients: [
      { item: "rice", qty: "3 cups, cooked and cooled" },
      { item: "eggs", qty: "2, beaten" },
      { item: "carrots", qty: "1/2 cup, diced" },
      { item: "onion", qty: "1/2, diced" },
      { item: "soy sauce", qty: "3 tbsp" },
      { item: "vegetable oil", qty: "2 tbsp" },
    ],
    steps: [
      "Scramble eggs in a hot wok with oil; set aside.",
      "Stir-fry carrots and onion 3 minutes.",
      "Add rice and soy sauce; toss until heated through, then fold eggs back in.",
    ],
  },
  {
    id: "quesadilla", name: "Pepper Quesadilla", type: "lunch",
    time: "15 min", serves: 2,
    ingredients: [
      { item: "tortillas", qty: "2 large" },
      { item: "cheese", qty: "1 cup" },
      { item: "bell pepper", qty: "1/2, sliced" },
      { item: "onion", qty: "1/4, sliced" },
      { item: "salsa", qty: "for serving" },
    ],
    steps: [
      "Saute bell pepper and onion until soft, about 5 minutes.",
      "Fill tortillas with cheese and vegetables; fold in half.",
      "Cook in a dry skillet 2-3 minutes per side until cheese melts. Serve with salsa.",
    ],
  },
  {
    id: "tomato-soup-grilled-cheese", name: "Tomato Soup + Grilled Cheese", type: "lunch",
    time: "30 min", serves: 4,
    ingredients: [
      { item: "canned tomatoes", qty: "28 oz can" },
      { item: "onion", qty: "1/2, diced" },
      { item: "garlic", qty: "2 cloves" },
      { item: "bread", qty: "8 slices" },
      { item: "cheese", qty: "8 slices" },
      { item: "butter", qty: "3 tbsp" },
    ],
    steps: [
      "Saute onion and garlic in butter; add tomatoes and simmer 15 minutes, then blend.",
      "Butter bread, sandwich with cheese, and grill until golden on both sides.",
      "Serve soup hot with the grilled cheese for dunking.",
    ],
  },
  {
    id: "lentil-soup", name: "Red Lentil Soup", type: "lunch",
    time: "35 min", serves: 4,
    ingredients: [
      { item: "lentils", qty: "1 1/2 cups" },
      { item: "carrots", qty: "2, diced" },
      { item: "celery", qty: "2 stalks, diced" },
      { item: "onion", qty: "1, diced" },
      { item: "garlic", qty: "3 cloves" },
      { item: "stock", qty: "6 cups" },
      { item: "cumin", qty: "1 tsp" },
    ],
    steps: [
      "Saute onion, carrots, celery, and garlic 5 minutes.",
      "Add lentils, stock, and cumin; simmer 25 minutes until lentils fall apart.",
      "Blend half for creaminess, season, and serve.",
    ],
  },
  {
    id: "chicken-noodle-soup", name: "Chicken Noodle Soup", type: "lunch",
    time: "40 min", serves: 4,
    ingredients: [
      { item: "chicken", qty: "2 breasts" },
      { item: "noodles", qty: "6 oz" },
      { item: "carrots", qty: "2, sliced" },
      { item: "celery", qty: "2 stalks, sliced" },
      { item: "onion", qty: "1/2, diced" },
      { item: "stock", qty: "8 cups" },
    ],
    steps: [
      "Simmer chicken in stock 20 minutes; shred and return to pot.",
      "Add carrots, celery, onion, and noodles; simmer 10 more minutes.",
      "Season with salt and pepper and serve hot.",
    ],
  },
  {
    id: "chickpea-grain-bowl", name: "Chickpea Grain Bowl", type: "lunch",
    time: "20 min", serves: 2,
    ingredients: [
      { item: "rice", qty: "2 cups, cooked" },
      { item: "chickpeas", qty: "1 can, drained" },
      { item: "cucumber", qty: "1/2, diced" },
      { item: "tomatoes", qty: "1 cup, halved" },
      { item: "lemon", qty: "1/2" },
      { item: "olive oil", qty: "2 tbsp" },
    ],
    steps: [
      "Crisp chickpeas in olive oil with salt and paprika, 8 minutes.",
      "Build bowls with rice, chickpeas, cucumber, and tomatoes.",
      "Dress with lemon juice and olive oil.",
    ],
  },
  {
    id: "blt", name: "Classic BLT", type: "lunch",
    time: "15 min", serves: 2,
    ingredients: [
      { item: "bacon", qty: "8 slices" },
      { item: "lettuce", qty: "4 leaves" },
      { item: "tomatoes", qty: "1, sliced" },
      { item: "bread", qty: "4 slices, toasted" },
      { item: "mayo", qty: "2 tbsp" },
    ],
    steps: [
      "Cook bacon until crisp; drain on paper towels.",
      "Spread mayo on toast.",
      "Stack bacon, lettuce, and tomato; close and slice.",
    ],
  },
  /* ---------------- DINNER ---------------- */
  {
    id: "spaghetti-marinara", name: "Spaghetti Marinara", type: "dinner",
    time: "30 min", serves: 4,
    ingredients: [
      { item: "pasta", qty: "12 oz" },
      { item: "canned tomatoes", qty: "28 oz can" },
      { item: "garlic", qty: "4 cloves" },
      { item: "onion", qty: "1/2, diced" },
      { item: "parmesan", qty: "1/2 cup" },
      { item: "olive oil", qty: "2 tbsp" },
      { item: "basil", qty: "a handful" },
    ],
    steps: [
      "Saute garlic and onion in olive oil 4 minutes.",
      "Add tomatoes; simmer 20 minutes, crushing with a spoon.",
      "Toss with cooked spaghetti, parmesan, and torn basil.",
    ],
  },
  {
    id: "chicken-alfredo", name: "Chicken Alfredo", type: "dinner",
    time: "30 min", serves: 4,
    ingredients: [
      { item: "pasta", qty: "12 oz" },
      { item: "chicken", qty: "1 lb, sliced" },
      { item: "cream", qty: "1 cup" },
      { item: "parmesan", qty: "3/4 cup" },
      { item: "garlic", qty: "3 cloves" },
      { item: "butter", qty: "3 tbsp" },
    ],
    steps: [
      "Sear chicken in butter until cooked through; set aside.",
      "Saute garlic, add cream, and simmer 3 minutes.",
      "Whisk in parmesan until smooth; toss with pasta and chicken.",
    ],
  },
  {
    id: "beef-tacos", name: "Beef Tacos", type: "dinner",
    time: "25 min", serves: 4,
    ingredients: [
      { item: "beef", qty: "1 lb" },
      { item: "tortillas", qty: "8 small" },
      { item: "onion", qty: "1/2, diced" },
      { item: "tomatoes", qty: "1, diced" },
      { item: "lettuce", qty: "2 cups, shredded" },
      { item: "cheese", qty: "1 cup" },
      { item: "salsa", qty: "1/2 cup" },
    ],
    steps: [
      "Brown beef with onion, chili powder, and cumin; drain.",
      "Warm tortillas in a dry skillet.",
      "Fill with beef, lettuce, tomatoes, cheese, and salsa.",
    ],
  },
  {
    id: "chicken-stir-fry", name: "Chicken Stir-Fry", type: "dinner",
    time: "25 min", serves: 4,
    ingredients: [
      { item: "chicken", qty: "1 lb, sliced" },
      { item: "broccoli", qty: "2 cups" },
      { item: "bell pepper", qty: "1, sliced" },
      { item: "garlic", qty: "2 cloves" },
      { item: "ginger", qty: "1 tbsp" },
      { item: "soy sauce", qty: "3 tbsp" },
      { item: "rice", qty: "2 cups, cooked" },
      { item: "vegetable oil", qty: "1 tbsp" },
    ],
    steps: [
      "Sear chicken in hot oil until browned, about 6 minutes; set aside.",
      "Stir-fry broccoli, bell pepper, garlic, and ginger 4 minutes.",
      "Return chicken, add soy sauce, and serve over rice.",
    ],
  },
  {
    id: "beef-broccoli", name: "Beef & Broccoli", type: "dinner",
    time: "25 min", serves: 4,
    ingredients: [
      { item: "beef", qty: "1 lb, thinly sliced" },
      { item: "broccoli", qty: "3 cups" },
      { item: "soy sauce", qty: "1/4 cup" },
      { item: "garlic", qty: "2 cloves" },
      { item: "rice", qty: "2 cups, cooked" },
    ],
    steps: [
      "Sear beef in a hot oiled skillet; set aside.",
      "Stir-fry broccoli with a splash of water until bright green.",
      "Return beef, add soy sauce and garlic, toss 2 minutes, serve over rice.",
    ],
  },
  {
    id: "shrimp-scampi", name: "Shrimp Scampi", type: "dinner",
    time: "20 min", serves: 4,
    ingredients: [
      { item: "shrimp", qty: "1 lb, peeled" },
      { item: "pasta", qty: "12 oz" },
      { item: "garlic", qty: "4 cloves" },
      { item: "butter", qty: "4 tbsp" },
      { item: "lemon", qty: "1/2" },
      { item: "parsley", qty: "2 tbsp" },
    ],
    steps: [
      "Cook pasta; reserve 1/2 cup pasta water.",
      "Saute garlic in butter 1 minute; add shrimp and cook 3 minutes.",
      "Toss with pasta, lemon juice, parsley, and pasta water as needed.",
    ],
  },
  {
    id: "salmon-roasted-veggies", name: "Salmon with Roasted Veggies", type: "dinner",
    time: "30 min", serves: 2,
    ingredients: [
      { item: "salmon", qty: "2 fillets" },
      { item: "potatoes", qty: "1 lb, cubed" },
      { item: "broccoli", qty: "2 cups" },
      { item: "olive oil", qty: "3 tbsp" },
      { item: "lemon", qty: "1/2" },
    ],
    steps: [
      "Toss potatoes and broccoli with olive oil and salt; roast at 425F for 15 minutes.",
      "Add salmon to the pan; roast 10 more minutes.",
      "Squeeze lemon over everything and serve.",
    ],
  },
  {
    id: "chicken-curry", name: "Chicken Curry", type: "dinner",
    time: "35 min", serves: 4,
    ingredients: [
      { item: "chicken", qty: "1 lb, cubed" },
      { item: "coconut milk", qty: "14 oz can" },
      { item: "curry powder", qty: "2 tbsp" },
      { item: "onion", qty: "1, diced" },
      { item: "rice", qty: "2 cups, cooked" },
    ],
    steps: [
      "Saute onion until soft; stir in curry powder 1 minute.",
      "Add chicken; cook 6 minutes.",
      "Pour in coconut milk and simmer 15 minutes. Serve over rice.",
    ],
  },
  {
    id: "chili", name: "Weeknight Chili", type: "dinner",
    time: "40 min", serves: 6,
    ingredients: [
      { item: "beef", qty: "1 lb" },
      { item: "beans", qty: "2 cans, drained" },
      { item: "canned tomatoes", qty: "28 oz can" },
      { item: "onion", qty: "1, diced" },
      { item: "chili powder", qty: "2 tbsp" },
      { item: "cumin", qty: "1 tsp" },
    ],
    steps: [
      "Brown beef with onion; drain fat.",
      "Stir in chili powder and cumin 1 minute.",
      "Add beans and tomatoes; simmer 25 minutes.",
    ],
  },
  {
    id: "pasta-primavera", name: "Pasta Primavera", type: "dinner",
    time: "25 min", serves: 4,
    ingredients: [
      { item: "pasta", qty: "12 oz" },
      { item: "zucchini", qty: "1, half-moons" },
      { item: "bell pepper", qty: "1, sliced" },
      { item: "tomatoes", qty: "1 cup, halved" },
      { item: "parmesan", qty: "1/2 cup" },
      { item: "olive oil", qty: "3 tbsp" },
    ],
    steps: [
      "Saute zucchini and bell pepper in olive oil 5 minutes.",
      "Add tomatoes; cook 2 more minutes.",
      "Toss with cooked pasta and parmesan.",
    ],
  },
  {
    id: "pork-fried-rice", name: "Pork Fried Rice", type: "dinner",
    time: "20 min", serves: 4,
    ingredients: [
      { item: "pork", qty: "1/2 lb, diced" },
      { item: "rice", qty: "3 cups, cooked and cooled" },
      { item: "eggs", qty: "2, beaten" },
      { item: "carrots", qty: "1/2 cup, diced" },
      { item: "soy sauce", qty: "3 tbsp" },
    ],
    steps: [
      "Brown pork in a hot wok; push aside and scramble eggs.",
      "Add carrots; stir-fry 3 minutes.",
      "Add rice and soy sauce; toss until steaming.",
    ],
  },
  {
    id: "stuffed-peppers", name: "Stuffed Bell Peppers", type: "dinner",
    time: "50 min", serves: 4,
    ingredients: [
      { item: "bell pepper", qty: "4, halved" },
      { item: "rice", qty: "1 1/2 cups, cooked" },
      { item: "beef", qty: "1/2 lb" },
      { item: "canned tomatoes", qty: "14 oz can" },
      { item: "cheese", qty: "1/2 cup" },
      { item: "onion", qty: "1/2, diced" },
    ],
    steps: [
      "Brown beef with onion; stir in rice and tomatoes.",
      "Fill pepper halves and top with cheese.",
      "Bake at 375F for 30 minutes until peppers are tender.",
    ],
  },
  {
    id: "mushroom-risotto", name: "Mushroom Risotto", type: "dinner",
    time: "40 min", serves: 4,
    ingredients: [
      { item: "rice", qty: "1 1/2 cups arborio" },
      { item: "mushrooms", qty: "8 oz, sliced" },
      { item: "onion", qty: "1/2, diced" },
      { item: "parmesan", qty: "3/4 cup" },
      { item: "butter", qty: "3 tbsp" },
      { item: "stock", qty: "5 cups, warm" },
    ],
    steps: [
      "Saute mushrooms in butter until browned; set aside.",
      "Cook onion and rice 2 minutes; add stock one ladle at a time, stirring, 20 minutes.",
      "Stir in mushrooms, parmesan, and butter. Rest 2 minutes and serve.",
    ],
  },
  {
    id: "chicken-fajitas", name: "Chicken Fajitas", type: "dinner",
    time: "25 min", serves: 4,
    ingredients: [
      { item: "chicken", qty: "1 lb, strips" },
      { item: "bell pepper", qty: "2, sliced" },
      { item: "onion", qty: "1, sliced" },
      { item: "tortillas", qty: "8 small" },
      { item: "lime", qty: "1" },
      { item: "cumin", qty: "1 tsp" },
    ],
    steps: [
      "Toss chicken and vegetables with oil, cumin, salt, and pepper.",
      "Sear in a screaming-hot skillet 8 minutes.",
      "Serve with warm tortillas and lime wedges.",
    ],
  },
  {
    id: "caprese-pasta", name: "Caprese Pasta", type: "dinner",
    time: "20 min", serves: 4,
    ingredients: [
      { item: "pasta", qty: "12 oz" },
      { item: "tomatoes", qty: "2 cups, halved" },
      { item: "mozzarella", qty: "8 oz, torn" },
      { item: "basil", qty: "1/2 cup" },
      { item: "olive oil", qty: "1/4 cup" },
    ],
    steps: [
      "Cook pasta; reserve 1/2 cup pasta water.",
      "Toss hot pasta with tomatoes, mozzarella, basil, and olive oil.",
      "Loosen with pasta water; season and serve.",
    ],
  },
];

/* A sample receipt so visitors can try the planner without uploading. */
const SAMPLE_RECEIPT_TEXT = [
  "FRESH CHICKEN BREAST 2.5 LB",
  "GROUND BEEF 1 LB",
  "BROCCOLI FLORETS 12 OZ",
  "BELL PEPPERS 3 CT",
  "ROMA TOMATOES 1 LB",
  "YELLOW ONIONS 2 LB",
  "GARLIC 1 HEAD",
  "LONG GRAIN RICE 2 LB",
  "SPAGHETTI 16 OZ",
  "FLOUR TORTILLAS 10 CT",
  "CHEDDAR CHEESE 8 OZ",
  "EGGS 12 CT",
].join("\n");
